import os
import json
import matplotlib.pyplot as plt
from fpdf import FPDF
from datetime import datetime

class BusinessImpactReport(FPDF):
    def header(self):
        # Dark background matching your theme
        self.set_fill_color(13, 17, 23) 
        self.rect(0, 0, 210, 297, 'F')
        self.set_font('Arial', 'B', 15)
        self.set_text_color(56, 189, 248) # Accent Blue
        self.cell(0, 10, 'SENTINEL: EXECUTIVE BUSINESS IMPACT REPORT', 0, 1, 'L')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(150)
        self.cell(0, 10, f'Page {self.page_no()} | Confidential AI Audit | Generated by Sentinel', 0, 0, 'C')

def generate_pdf_report(repo_name, data):
    # --- RECURSIVE SAFETY CHECK ---
    def drill_to_dict(obj):
        if isinstance(obj, list) and len(obj) > 0:
            return drill_to_dict(obj[0])
        return obj if isinstance(obj, dict) else {}

    data = drill_to_dict(data)
    
    # Ensure reports directory exists
    if not os.path.exists('reports'):
        os.makedirs('reports')
    
    # Now this line will NEVER fail
    forecast = data.get('financial_forecasting', data.get('revenue_model', {}))
    forecast = drill_to_dict(forecast) # Double check sub-object
    # --- ULTRA-DEFENSIVE LAYER: THE RECURSIVE UNWRAPPER ---
    def force_to_dict(obj):
        """Recursively drills into lists to find the first available dictionary."""
        if isinstance(obj, list):
            return force_to_dict(obj[0]) if len(obj) > 0 else {}
        return obj

    # Standardize the main data object
    data = force_to_dict(data)
    
    # Ensure reports directory exists
    if not os.path.exists('reports'):
        os.makedirs('reports')

    pdf = BusinessImpactReport()
    pdf.add_page()
    
    # --- PAGE 1: FINANCIAL EXPOSURE ---
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Arial', 'B', 24)
    pdf.cell(0, 20, f"Project: {repo_name}", 0, 1, 'L')
    
    # Extract sub-objects safely
    forecast = force_to_dict(data.get('financial_forecasting', {}))
    # Fallback to revenue_model if financial_forecasting is missing
    if not forecast:
        forecast = force_to_dict(data.get('revenue_model', {}))

    pdf.set_font('Arial', '', 12)
    pdf.set_fill_color(30, 41, 59) 
    
    stats = [
        ["Annual Revenue Leak", f"${forecast.get('annual_burn', forecast.get('monthly_loss_total', 0) * 12):,}"],
        ["Monthly Technical Tax", f"${forecast.get('complexity_tax', forecast.get('tech_tax', 0)):,}"],
        ["Workforce Efficiency", forecast.get('efficiency_multiplier', forecast.get('efficiency', 'N/A'))],
        ["Audit Timestamp", datetime.now().strftime("%Y-%b-%d %H:%M")]
    ]
    
    for row in stats:
        pdf.set_text_color(200, 200, 200)
        pdf.cell(80, 12, f" {row[0]}", 1, 0, 'L', True)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(110, 12, f"{row[1]} ", 1, 1, 'R', True)

    pdf.ln(10)

    # --- BAR GRAPH: LOSS DISTRIBUTION ---
    plt.style.use('dark_background')
    plt.figure(figsize=(6, 4))
    
    categories = ['Debt Tax', 'Churn Waste', 'Bug Leak']
    values = [
        forecast.get('complexity_tax', forecast.get('tech_tax', 0)), 
        forecast.get('churn_waste', 0), 
        forecast.get('stability_drain', forecast.get('stability_leak', 0))
    ]
    
    plt.bar(categories, values, color='#38bdf8', edgecolor='white', linewidth=0.5)
    plt.title("Economic Loss Breakdown (Monthly)", fontsize=14, color='#38bdf8', pad=20)
    plt.ylabel("USD ($)")
    
    # Use a safe filename
    safe_repo_name = repo_name.replace("/", "_").replace("\\", "_")
    chart_filename = f"temp_chart_{safe_repo_name}.png"
    plt.savefig(chart_filename, bbox_inches='tight', dpi=150)
    plt.close()
    
    pdf.image(chart_filename, x=15, y=110, w=180)
    
    if os.path.exists(chart_filename):
        os.remove(chart_filename)

    # --- PAGE 2: STRATEGIC REMEDIATION ---
    pdf.add_page()
    pdf.set_font('Arial', 'B', 20)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 15, "Strategic ROI Recovery Plan", 0, 1, 'L')
    pdf.ln(5)
    
    exec_sum = force_to_dict(data.get('executive_summary', {}))
    pillars = exec_sum.get('strategic_pillars', [])
    
    if not isinstance(pillars, list):
        pillars = []
    
    if not pillars:
        pdf.set_font('Arial', 'I', 11)
        pdf.cell(0, 10, "Detailed remediation steps pending agent completion...", 0, 1)
    else:
        for p in pillars:
            p = force_to_dict(p)
            if not p: continue
                
            pdf.set_font('Arial', 'B', 13)
            pdf.set_text_color(56, 189, 248)
            pdf.cell(0, 10, f"TARGET: {p.get('pillar_name', 'System Optimization').upper()}", 0, 1)
            
            pdf.set_font('Arial', '', 11)
            pdf.set_text_color(230, 230, 230)
            
            val_text = f"Business Value: {p.get('business_value', 'Recovery of developer velocity.')}"
            action_text = f"Executive Action: {p.get('ceo_action', 'Review technical debt backlog with Engineering Lead.')}"
            
            pdf.multi_cell(0, 7, f"{val_text}\n{action_text}")
            pdf.ln(6)

    output_path = f"reports/Business_Impact_{safe_repo_name}.pdf"
    pdf.output(output_path)
    return output_path